/*
 * Copyright (c) 2023 Institute of Parallel And Distributed Systems (IPADS), Shanghai Jiao Tong University (SJTU)
 * Licensed under the Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *     http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY OR FIT FOR A PARTICULAR
 * PURPOSE.
 * See the Mulan PSL v2 for more details.
 */

// USPi - An USB driver for Raspberry Pi written in C
// Copyright (C) 2014-2016  R. Stange <rsta2@o2online.de>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

#include <chcore/type.h>

#include "xkbcommon-keysyms.h"

const u32 keymap_us[128][2] = {
        {XKB_KEY_VoidSymbol, XKB_KEY_VoidSymbol},
        {XKB_KEY_VoidSymbol, XKB_KEY_VoidSymbol},
        {XKB_KEY_VoidSymbol, XKB_KEY_VoidSymbol},
        {XKB_KEY_VoidSymbol, XKB_KEY_VoidSymbol},
        {XKB_KEY_a, XKB_KEY_A},
        {XKB_KEY_b, XKB_KEY_B},
        {XKB_KEY_c, XKB_KEY_C},
        {XKB_KEY_d, XKB_KEY_D},
        {XKB_KEY_e, XKB_KEY_E},
        {XKB_KEY_f, XKB_KEY_F},
        {XKB_KEY_g, XKB_KEY_G},
        {XKB_KEY_h, XKB_KEY_H},
        {XKB_KEY_i, XKB_KEY_I},
        {XKB_KEY_j, XKB_KEY_J},
        {XKB_KEY_k, XKB_KEY_K},
        {XKB_KEY_l, XKB_KEY_L},
        {XKB_KEY_m, XKB_KEY_M},
        {XKB_KEY_n, XKB_KEY_N},
        {XKB_KEY_o, XKB_KEY_O},
        {XKB_KEY_p, XKB_KEY_P},
        {XKB_KEY_q, XKB_KEY_Q},
        {XKB_KEY_r, XKB_KEY_R},
        {XKB_KEY_s, XKB_KEY_S},
        {XKB_KEY_t, XKB_KEY_T},
        {XKB_KEY_u, XKB_KEY_U},
        {XKB_KEY_v, XKB_KEY_V},
        {XKB_KEY_w, XKB_KEY_W},
        {XKB_KEY_x, XKB_KEY_X},
        {XKB_KEY_y, XKB_KEY_Y},
        {XKB_KEY_z, XKB_KEY_Z},
        {XKB_KEY_1, XKB_KEY_exclam},
        {XKB_KEY_2, XKB_KEY_at},
        {XKB_KEY_3, XKB_KEY_numbersign},
        {XKB_KEY_4, XKB_KEY_dollar},
        {XKB_KEY_5, XKB_KEY_percent},
        {XKB_KEY_6, XKB_KEY_caret},
        {XKB_KEY_7, XKB_KEY_ampersand},
        {XKB_KEY_8, XKB_KEY_asterisk},
        {XKB_KEY_9, XKB_KEY_parenleft},
        {XKB_KEY_0, XKB_KEY_parenright},
        {XKB_KEY_Return, XKB_KEY_Return},
        {XKB_KEY_Escape, XKB_KEY_Escape},
        {XKB_KEY_BackSpace, XKB_KEY_BackSpace},
        {XKB_KEY_Tab, XKB_KEY_Tab},
        {XKB_KEY_space, XKB_KEY_space},
        {XKB_KEY_minus, XKB_KEY_underscore},
        {XKB_KEY_equal, XKB_KEY_plus},
        {XKB_KEY_bracketleft, XKB_KEY_braceleft},
        {XKB_KEY_bracketright, XKB_KEY_braceright},
        {XKB_KEY_backslash, XKB_KEY_bar},
        {XKB_KEY_numbersign, XKB_KEY_asciitilde},
        {XKB_KEY_semicolon, XKB_KEY_colon},
        {XKB_KEY_quoteright, XKB_KEY_quotedbl},
        {XKB_KEY_quoteleft, XKB_KEY_asciitilde},
        {XKB_KEY_comma, XKB_KEY_less},
        {XKB_KEY_period, XKB_KEY_greater},
        {XKB_KEY_slash, XKB_KEY_question},
        {XKB_KEY_Caps_Lock, XKB_KEY_Caps_Lock},
        {XKB_KEY_F1, XKB_KEY_VoidSymbol},
        {XKB_KEY_F2, XKB_KEY_VoidSymbol},
        {XKB_KEY_F3, XKB_KEY_VoidSymbol},
        {XKB_KEY_F4, XKB_KEY_VoidSymbol},
        {XKB_KEY_F5, XKB_KEY_VoidSymbol},
        {XKB_KEY_F6, XKB_KEY_VoidSymbol},
        {XKB_KEY_F7, XKB_KEY_VoidSymbol},
        {XKB_KEY_F8, XKB_KEY_VoidSymbol},
        {XKB_KEY_F9, XKB_KEY_VoidSymbol},
        {XKB_KEY_F10, XKB_KEY_VoidSymbol},
        {XKB_KEY_F11, XKB_KEY_VoidSymbol},
        {XKB_KEY_F12, XKB_KEY_VoidSymbol},
        {XKB_KEY_Print, XKB_KEY_VoidSymbol},
        {XKB_KEY_Scroll_Lock, XKB_KEY_VoidSymbol},
        {XKB_KEY_Pause, XKB_KEY_VoidSymbol},
        {XKB_KEY_Insert, XKB_KEY_VoidSymbol},
        {XKB_KEY_Home, XKB_KEY_VoidSymbol},
        {XKB_KEY_Page_Up, XKB_KEY_VoidSymbol},
        {XKB_KEY_Delete, XKB_KEY_VoidSymbol},
        {XKB_KEY_End, XKB_KEY_VoidSymbol},
        {XKB_KEY_Page_Down, XKB_KEY_VoidSymbol},
        {XKB_KEY_Right, XKB_KEY_VoidSymbol},
        {XKB_KEY_Left, XKB_KEY_VoidSymbol},
        {XKB_KEY_Down, XKB_KEY_VoidSymbol},
        {XKB_KEY_Up, XKB_KEY_VoidSymbol},
        {XKB_KEY_Num_Lock, XKB_KEY_Num_Lock},
        {XKB_KEY_KP_Divide, XKB_KEY_KP_Divide},
        {XKB_KEY_KP_Multiply, XKB_KEY_KP_Multiply},
        {XKB_KEY_KP_Subtract, XKB_KEY_KP_Subtract},
        {XKB_KEY_KP_Add, XKB_KEY_KP_Add},
        {XKB_KEY_KP_Enter, XKB_KEY_KP_Enter},
        {XKB_KEY_End, XKB_KEY_KP_1},
        {XKB_KEY_Down, XKB_KEY_KP_2},
        {XKB_KEY_Page_Down, XKB_KEY_KP_3},
        {XKB_KEY_Left, XKB_KEY_KP_4},
        {XKB_KEY_VoidSymbol, XKB_KEY_KP_5},
        {XKB_KEY_Right, XKB_KEY_KP_6},
        {XKB_KEY_Home, XKB_KEY_KP_7},
        {XKB_KEY_Up, XKB_KEY_KP_8},
        {XKB_KEY_Page_Up, XKB_KEY_KP_9},
        {XKB_KEY_Insert, XKB_KEY_KP_0},
        {XKB_KEY_Delete, XKB_KEY_KP_Decimal},
        {XKB_KEY_backslash, XKB_KEY_bar},
        {XKB_KEY_VoidSymbol, XKB_KEY_VoidSymbol},
        {XKB_KEY_VoidSymbol, XKB_KEY_VoidSymbol},
        {XKB_KEY_VoidSymbol, XKB_KEY_VoidSymbol},
        {XKB_KEY_VoidSymbol, XKB_KEY_VoidSymbol},
        {XKB_KEY_VoidSymbol, XKB_KEY_VoidSymbol},
        {XKB_KEY_VoidSymbol, XKB_KEY_VoidSymbol},
        {XKB_KEY_VoidSymbol, XKB_KEY_VoidSymbol},
        {XKB_KEY_VoidSymbol, XKB_KEY_VoidSymbol},
        {XKB_KEY_VoidSymbol, XKB_KEY_VoidSymbol},
        {XKB_KEY_VoidSymbol, XKB_KEY_VoidSymbol},
        {XKB_KEY_VoidSymbol, XKB_KEY_VoidSymbol},
        {XKB_KEY_VoidSymbol, XKB_KEY_VoidSymbol},
        {XKB_KEY_VoidSymbol, XKB_KEY_VoidSymbol},
        {XKB_KEY_VoidSymbol, XKB_KEY_VoidSymbol},
        {XKB_KEY_VoidSymbol, XKB_KEY_VoidSymbol},
        {XKB_KEY_VoidSymbol, XKB_KEY_VoidSymbol},
        {XKB_KEY_VoidSymbol, XKB_KEY_VoidSymbol},
        {XKB_KEY_VoidSymbol, XKB_KEY_VoidSymbol},
        {XKB_KEY_VoidSymbol, XKB_KEY_VoidSymbol},
        {XKB_KEY_VoidSymbol, XKB_KEY_VoidSymbol},
        {XKB_KEY_VoidSymbol, XKB_KEY_VoidSymbol},
        {XKB_KEY_VoidSymbol, XKB_KEY_VoidSymbol},
        {XKB_KEY_VoidSymbol, XKB_KEY_VoidSymbol},
        {XKB_KEY_VoidSymbol, XKB_KEY_VoidSymbol},
        {XKB_KEY_VoidSymbol, XKB_KEY_VoidSymbol},
        {XKB_KEY_VoidSymbol, XKB_KEY_VoidSymbol},
        {XKB_KEY_VoidSymbol, XKB_KEY_VoidSymbol},
};
