stages:
  - trigger_downstream

downstream:
  stage: trigger_downstream
  trigger: 
    project: staros/staros
    strategy: depend
  variables:
    STAROS_COMPONENT_NAME: kernel
    STAROS_COMPONENT_BRANCH: ${CI_COMMIT_REF_NAME}
    STAROS_MR_LABELS: ${CI_MERGE_REQUEST_LABELS}
  rules:
    - if: $CI_MERGE_REQUEST_LABELS !~ /.*MR-link-main.*/ && ($CI_PIPELINE_SOURCE == 'web' || $CI_PIPELINE_SOURCE == 'merge_request_event')

downstream_link_main:
  stage: trigger_downstream
  trigger: 
    project: staros/staros
    strategy: depend
    branch: ${CI_COMMIT_REF_NAME}
  variables:
    STAROS_COMPONENT_NAME: kernel
    STAROS_COMPONENT_BRANCH: ${CI_COMMIT_REF_NAME}
    STAROS_MR_LABELS: ${CI_MERGE_REQUEST_LABELS}
  rules:
    - if: $CI_MERGE_REQUEST_LABELS =~ /.*MR-link-main.*/  && ($CI_PIPELINE_SOURCE == 'web' || $CI_PIPELINE_SOURCE == 'merge_request_event')

