name: Lab2

on:
  push:
    branches:
      - 'main'
    paths:
      - Lab2/**
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: ipads/oslab:24.09
      options: --user 1001
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Build Lab2
        run: cd Lab2 && make
